//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModManagerDLC.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModManagerDLC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- ELS VEHICLE CONFIGURATION FILE --&gt;
        ///&lt;vcfroot Description=&quot;Sample VCF&quot; Author=&quot;Luxart&quot; &gt;
        ///	&lt;!-- INTERFACE --&gt;
        ///	&lt;INTERFACE&gt;
        ///		&lt;LstgActivationType&gt;manual&lt;/LstgActivationType&gt;
        ///		&lt;DefaultSirenMode&gt;standby&lt;/DefaultSirenMode&gt;
        ///		&lt;InfoPanelHeaderColor&gt;grey&lt;/InfoPanelHeaderColor&gt;
        ///		&lt;InfoPanelButtonLightColor&gt;orange&lt;/InfoPanelButtonLightColor&gt;
        ///	&lt;/INTERFACE&gt;
        ///	&lt;!-- EXTRAS OVERRIDE AND ENV LIGHTING--&gt;
        ///	&lt;EOVERRIDE&gt;	
        ///		&lt;Extra01 IsElsControlled=&quot;true&quot; AllowEnvLight=&quot;true [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string els_template {
            get {
                return ResourceManager.GetString("els_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Item type=&quot;CHandlingData&quot;&gt;
        ///      &lt;handlingName&gt;police&lt;/handlingName&gt;
        ///      &lt;fMass value=&quot;3400.0&quot; /&gt;
        ///      &lt;fInitialDragCoeff value=&quot;0.7800000&quot; /&gt;
        ///      &lt;fPercentSubmerged value=&quot;85.000000&quot; /&gt;
        ///      &lt;vecCentreOfMassOffset x=&quot;0.000000&quot; y=&quot;0.000000&quot; z=&quot;0.000000&quot; /&gt;
        ///      &lt;vecInertiaMultiplier x=&quot;1.000000&quot; y=&quot;1.300000&quot; z=&quot;1.500000&quot; /&gt;
        ///      &lt;fDriveBiasFront value=&quot;0.300000&quot; /&gt;
        ///      &lt;nInitialDriveGears value=&quot;6&quot; /&gt;
        ///      &lt;fInitialDriveForce value=&quot;0.320000&quot; /&gt;
        ///      &lt;fDriveInertia value=&quot;1.000000&quot; /&gt; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string handling_duster {
            get {
                return ResourceManager.GetString("handling_duster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a     &lt;Item type=&quot;CHandlingData&quot;&gt;
        ///      &lt;handlingName&gt;police2&lt;/handlingName&gt;
        ///			&lt;fMass value=&quot;3400.0&quot; /&gt;
        ///			&lt;fInitialDragCoeff value=&quot;0.7800000&quot; /&gt;
        ///			&lt;fPercentSubmerged value=&quot;85.000000&quot; /&gt;
        ///			&lt;vecCentreOfMassOffset x=&quot;0.000000&quot; y=&quot;0.000000&quot; z=&quot;0.000000&quot; /&gt;
        ///			&lt;vecInertiaMultiplier x=&quot;1.000000&quot; y=&quot;1.300000&quot; z=&quot;1.500000&quot; /&gt;
        ///			&lt;fDriveBiasFront value=&quot;0.300000&quot; /&gt;
        ///			&lt;nInitialDriveGears value=&quot;5&quot; /&gt;
        ///			&lt;fInitialDriveForce value=&quot;0.320000&quot; /&gt;
        ///			&lt;fDriveInertia value=&quot;0.400000&quot; /&gt;
        ///			&lt;fClutchChangeRat [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string handling_s10 {
            get {
                return ResourceManager.GetString("handling_s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;CHandlingDataMgr&gt;
        ///	&lt;HandlingData&gt;
        ///    &lt;Item type=&quot;CHandlingData&quot;&gt;
        ///      &lt;handlingName&gt;trail22pcespg2&lt;/handlingName&gt;
        ///      &lt;fMass value=&quot;3400.0&quot; /&gt;
        ///      &lt;fInitialDragCoeff value=&quot;7.7800000&quot; /&gt;
        ///      &lt;fPercentSubmerged value=&quot;85.000000&quot; /&gt;
        ///      &lt;vecCentreOfMassOffset x=&quot;0.000000&quot; y=&quot;0.000000&quot; z=&quot;-0.500000&quot; /&gt;
        ///      &lt;vecInertiaMultiplier x=&quot;1.000000&quot; y=&quot;1.300000&quot; z=&quot;1.500000&quot; /&gt;
        ///      &lt;fDriveBiasFront value=&quot;0.300000&quot; /&gt;
        ///      &lt;nInitialDriveGears value=&quot;6&quot; / [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string handling_trail {
            get {
                return ResourceManager.GetString("handling_trail", resourceCulture);
            }
        }
    }
}
